---

- name: Install avahi
  pkgng:
    name: "{{ avahi_package }}"
    state: present

- name: Install avahi_mdns_packages
  pkgng:
    name: "{{ item }}"
    state: present
  with_items: "{{ avahi_mdns_packages }}"

- name: Enable avahi-daemon
  service:
    name: "{{ avahi_daemon_service }}"
    enabled: yes
