---
# tasks file for ansible-role-avahi

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ avahi_log_dir }}"
    mode: 0755
    owner: "{{ avahi_user }}"
    group: "{{ avahi_group }}"
    state: directory
  notify: Restart avahi

- name: Create db directory
  file:
    path: "{{ avahi_db_dir }}"
    mode: 0755
    owner: "{{ avahi_user }}"
    group: "{{ avahi_group }}"
    state: directory
  notify: Restart avahi

- name: Create avahi.conf
  template:
    src: avahi.conf.j2
    dest: "{{ avahi_conf_file }}"
    validate: echo %s
  notify: Restart avahi

- name: Start avahi
  service:
    name: "{{ avahi_service }}"
    enabled: true
    state: started
